site_name: Ornament documentation

pages:
- Home:
    - 'Quick start': 'index.md'

- Basic:
    - 'Overview of concepts and functionalities': 'basic/overview.md'
    - 'Writing Ornament models from scratch': 'basic/scratch.md'
    - 'Adding virtual fields': 'basic/virtual.md'
    - 'Generating ORM models': 'basic/generating.md'

- 'Tutorial: writing a simple Twitter client':
    - 'Dependencies': 'tutorial/dependencies.md'
    - 'Tweet model': 'tutorial/tweet.md'

theme: mkdocs
