site_name: 'Ornament documentation'
pages:
    -
        Home:
            -
                'Quick start': index.md
    -
        Basic:
            -
                'Overview of concepts and functionalities': basic/overview.md
            -
                'Writing Ornament models from scratch': basic/scratch.md
            -
                'Adding virtual fields': basic/virtual.md
            -
                'Getting data into your models': basic/loading.md
    -
        Joining forces:
            -
                'Getting data from more than one source': joining/straight.md
            -
                'Cascading queries': joining/cascade.md

    -
        Advanced:
            -
                'Exporting JSON': advanced/json.md
            -
                'Writing your own adapters': advanced/adapters.md
            -
                'Using Collections': advanced/collection.md
            -
                'Marker interfaces': advanced/markers.md
            -
                'Observer pattern': advanced/observer.md

theme: mkdocs
